---
name: permision_provider
---
SilverStripe\Security\Group:
  extensions:
    - Sunnysideup\PermissionProvider\Extensions\GroupExtension
  summary_fields:
    Title: Title
    Parent.Title: Parent
    Members.Count: Members
  default_sort: "Sort ASC"

SilverStripe\Security\PermissionRole:
  extensions:
    - Sunnysideup\PermissionProvider\Extensions\RoleExtension

SilverStripe\Security\MemberAuthenticator\LoginHandler:
  extensions:
    - Sunnysideup\PermissionProvider\Extensions\LoginHandlerExtension
